#生产环境
spring:
  profiles: uat
  #数据源配置
  datasource:
    url: jdbc:mysql://139.159.142.50:7002/chaisdb2
    username: chais
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  #缓存配置
  redis:
    host: 139.159.142.50
    password: jdbrd@1302
    port: 46379
    timeout: 3000
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
  #消息中间件
  rabbitmq:
    host: 139.159.142.50
    port: 45672
    username: chh_global_message
    password: chh_global_message@301
    virtual-host: /chh_global_message
      #手动ACK 不开启自动ACK模式,目的是防止报错后未正确处理消息丢失 默认 为 none
    listener:
      simple:
        acknowledge-mode: manual
  http:
    multipart:
    max-file-size: 10MB
    max-request-size: 10MB
file:
  uploadFolder: /uploadfiles
#服务端口配置
server:
  port: 8686
  servlet:
    session:
      timeout: 1000
  server-header:
    #修改请求头容量大小，防止报错
    maxHttpHeaderSize: 20 * 1024
